Fix link to DOCUMENTATION.md
gocardless/gocardless-legacy-php pull request #48
Opened 2016-10-06 14:14 UTC by sampart

Now correctly points to the legacy repository rather than 404ing.

2016-10-06 15:29 UTC, timrogers requested changes
Thanks so much :+1: Just a little tweak and then we can get this in

2016-10-06 15:29 UTC, timrogers commented on README.md
> +If you're sure this is the library you want to be using, see [DOCUMENTATION.md](DOCUMENTATION.md) for documentation and helpful resources.
I think you'll need to add the full URL (albeit with the right repository name), else this link won't work on GitHub

2016-10-06 15:31 UTC, sampart commented on README.md
> +If you're sure this is the library you want to be using, see [DOCUMENTATION.md](DOCUMENTATION.md) for documentation and helpful resources.
Ah, okay.  I've amended the commit and force-pushed.

2017-08-08 10:03 UTC, sampart commented
Looks like someone else fixed this already: https://github.com/gocardless/gocardless-legacy-php/commit/9e4e9a3c48f2885ade6463fceb8f5fc0421d3cf4

2017-08-08 10:03 UTC, closed without merging